name: Get OIDC Token
on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get OIDC Token
        run: |
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=oai-coding-agent-github-action" | jq -r '.value')

          # helper that converts base64-URL → base64 and decodes with OpenSSL (no padding errors)
          b64url_decode () {
            printf '%s' "$1" | tr '_-' '/+' | openssl base64 -d -A 2>/dev/null
          }

          payload=$(b64url_decode "$(cut -d. -f2 <<<"$TOKEN")")

          iat=$(jq -r '.iat' <<<"$payload")
          exp=$(jq -r '.exp' <<<"$payload")
          echo "iat : $iat"
          echo "exp : $exp"
          echo "TTL : $((exp - iat)) seconds"

          echo "$TOKEN" > oidc_token.txt
      - name: Upload token as artifact
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: oidc_token.txt
