name: Get OIDC Token
on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get OIDC Token
        run: |
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=my-github-app" | jq -r '.value')
          echo "OIDC Token (copy this for local testing):"
          echo "$TOKEN"
