name: Get OIDC Token
on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get OIDC Token
        run: |
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=test" | jq -r '.value')
          echo "$TOKEN" > oidc_token.txt
      - name: Upload token as artifact
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: oidc_token.txt
